#+ summary: Wolfender's lab publications
#+ description: Wolfender's lab publications
#+ endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql
#+ pagination: 100
#+ method: GET
#+ tags:
#+   - Jean-Luc Wolfender
#+   - Publications
#+   - Wikidata
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wds: <http://www.wikidata.org/entity/statement/>
PREFIX wdv: <http://www.wikidata.org/value/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>

PREFIX wdref: <http://www.wikidata.org/reference/>
PREFIX psv: <http://www.wikidata.org/prop/statement/value/>
PREFIX psn: <http://www.wikidata.org/prop/statement/value-normalized/>
PREFIX pqv: <http://www.wikidata.org/prop/qualifier/value/>
PREFIX pqn: <http://www.wikidata.org/prop/qualifier/value-normalized/>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prv: <http://www.wikidata.org/prop/reference/value/>
PREFIX prn: <http://www.wikidata.org/prop/reference/value-normalized/>
PREFIX wdno: <http://www.wikidata.org/prop/novalue/>
PREFIX wdata: <http://www.wikidata.org/wiki/Special:EntityData/>

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX gas: <http://www.bigdata.com/rdf/gas#>
PREFIX hint: <http://www.bigdata.com/queryHints#>
#title:Wolfender's lab publications
SELECT DISTINCT (MIN(?dates) AS ?date) ?title ?journal ?doi ?work (GROUP_CONCAT(DISTINCT ?authorLabel; SEPARATOR = ", ") AS ?authors)
WITH {
  SELECT DISTINCT ?work ?datetimes WHERE {
    VALUES ?lab {
      wd:Q56084663
      wd:Q87644493
      wd:Q43275441
    }
    VALUES ?year {
      20
    }
    ?work wdt:P50 ?lab;
          wdt:P577 ?datetimes. 
          FILTER(YEAR(?datetimes) >= YEAR(NOW()) - ?year)
  } 
} AS %works 
WITH {
  SELECT DISTINCT ?work ?author_statement ?dates ?doi ?journal ?title WHERE {
    INCLUDE %works   
            ?work 
            wdt:P1433 ?journal_;
            wdt:P356 ?doi;
            p:P50 ?author_statement.
    BIND(xsd:date(?datetimes) AS ?dates)
    SERVICE wikibase:label {
      bd:serviceParam wikibase:language "en".
      ?journal_ rdfs:label ?journal.
      ?work rdfs:label ?title.
    } 
  }
} AS %author_statements
WHERE {    
  SELECT DISTINCT ?authorLabel ?order ?dates ?title ?journal ?doi ?work WHERE {
  INCLUDE %author_statements   
    ?author_statement ps:P50 ?author;
                      pq:P1545 ?order_.
    BIND(xsd:integer(?order_) AS ?order)
    SERVICE wikibase:label {
      bd:serviceParam wikibase:language "en".
      ?author rdfs:label ?authorLabel. 
    } 
  }
  ORDER BY (?order)
}
GROUP BY ?title ?journal ?doi ?work
ORDER BY DESC (?date) 